-- Run this in your Supabase SQL Editor

CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    league TEXT NOT NULL,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    time TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create a unique constraint to allow upserting (updating if exists)
CREATE UNIQUE INDEX matches_unique_idx ON matches (date, home_team, away_team);

-- Optional: Enable Row Level Security (RLS) if you plan to expose this to frontend
-- ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read access for all users" ON matches FOR SELECT USING (true);
